name: Deploy Static Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload website files
        uses: actions/upload-artifact@v4
        with:
          name: static-website
          path: ./ 

      - name: List directory contents
        run: ls -R
            
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: static-website
          preview: false
